### ISSUE TITLE
Command-line generator attempts to include any trailing comments as include file names

### ISSUE THREAD

**Issue by ageoghegan** [mulesoft-labs/raml-dotnet-tools#142]
I have external RAML files referenced in a relative path like so:
```
uses:
  Requests: library/requests.raml
  Responses: library/responses.raml
  Base: library/baseTypes.raml
```
This is working fine now, however when the command line generator tries to parse the included files I get this error:
**starting generator
Error: Could not find file '&lt;path&gt;\\# A set of common base type definitions'.**
This is weird, but not so weird when I check the contents of the first included file _requests.raml_:
The first operative line in that included file also tries to include the baseTypes.raml file so:
```
uses:
  Base: baseTypes.raml      # A set of common base type definitions
```
For some reason the parser is not exc;luding the comment and treating it as part of an included file path.
