### ISSUE TITLE
RAMLGen: Error generating client with valid API file from Anypoint

### ISSUE THREAD

**Issue by richardcase** [mulesoft-labs/raml-dotnet-tools#154]
I am using RAMLGen (0.1.0.0) from the command line to try and generate a client from a API definition (RAML 1.0) downloaded from Anypoint API Manager. The API definition is valid according to the API editor in the API Manager and also in Anypoint Studio.

However when i run RAMLGen i am receiving the following error:

`Error: Object reference not set to an instance of an object.`

The command line i am using is:

`RAMLGen.exe client -s C:\dev\code\currentpricenonmodular\src\main\api\api.raml`

I get the same error if i use the VS Tools in VS2015.

**Comment by woodp** [comment]
could you provide the RAML spec ?

**Comment by richardcase** [comment]
Sure, here is a sanitized version that causes the same error:

[api2.zip](https://github.com/mulesoft-labs/raml-dotnet-tools/files/1010839/api2.zip)

**Comment by richardcase** [comment]
The issue is caused by this in the API:
```
  productPriceWithVariantsResponse:
    type: productPriceResponse
    properties:
      variantprices:
        type: array
        items: variantPrice
        required: false
```
If i change the definition to the following it works:
```
  productPriceWithVariantsResponse:
    type: productPriceResponse
    properties:
      variantprices:
        type: variantPrice[]
        required: false
```
