### ISSUE TITLE
Add RegularExpressionAttribute when pattern is defined in Raml property

### ISSUE THREAD

**Issue by amikhaildev** [mulesoft-labs/raml-dotnet-tools#187]
When defining types in Raml we can define "pattern" for a string property which defined "Regular expression that this string SHOULD match.", however when generating code from Raml it doesn't add RegularExpression attribute in generated class
for example

```
SampleClass:
    properties: 
      AlphaNumeric:
        type: string
        pattern: ^[a-zA-Z0-9]{3}$
```

Generated
```
    public partial class RequestSampleClass
    {
        

        [Required]
        public string AlphaNumeric { get; set; }
    } // end class
```

My expectation is it should also add RegularExpression attribute, so generated code should be 
```
    public partial class RequestSampleClass
    {
        
        [RegularExpression("^[a-zA-Z0-9]{3}$")]
        [Required]
        public string AlphaNumeric { get; set; }
    } // end class
```
