### ISSUE TITLE
Enum values from reserved words cannot be deserialized

### ISSUE THREAD

**Issue by majkimester** [mulesoft-labs/raml-dotnet-tools#197]
We have an enum with reserved words:

```
  ParameterMeta:
    properties:
      paramName:
        type: string
      label:
        type: string
      paramType:
        type: string
        enum: [Integer, String, Bool, DateTime, Enum]
```
The generator put an Ip prefix for the reserved words and the generated enum looks like:

```
	public enum ParamType
	{
		[JsonProperty("Integer")]
		Integer,
		[JsonProperty("String")]
		Ipstring,
		[JsonProperty("Bool")]
		Ipbool,
		[JsonProperty("DateTime")]
		DateTime,
		[JsonProperty("Enum")]
		Enum
    }
```

The newtonsoft JSON cannot deserialize a valid JSON into this enum type.
It requres EnumMember attribute instead of the JsonProperty.

It can be fixed in the RAMLClient.t4 template:

```
	public enum <#= apiEnum.Name #>
	{
<#
	var i = 1;
	foreach (var property in apiEnum.Values)
	{
#>
		[JsonProperty("<#= property.OriginalName #>")]
		[EnumMember(Value = "<#= property.OriginalName #>")]
		<#= property.Name #><#= i < apiEnum.Values.Count() ? "," : string.Empty #>
<#	
		i++;
	}
```

And the result works fine:

```
	public enum Tipus
	{
		[JsonProperty("Integer")]
		[EnumMember(Value = "Integer")]
		Integer,
		[JsonProperty("String")]
		[EnumMember(Value = "String")]
		Ipstring,
		[JsonProperty("Bool")]
		[EnumMember(Value = "Bool")]
		Ipbool,
		[JsonProperty("DateTime")]
		[EnumMember(Value = "DateTime")]
		DateTime,
		[JsonProperty("Enum")]
		[EnumMember(Value = "Enum")]
		Enum
    }
```
