### ISSUE TITLE
RAML tool does not work on "bare" arrays

### ISSUE THREAD

**Issue by tb-wwparker** [mulesoft-labs/raml-dotnet-tools#34]
If you try to import a schema with a bare array (something like `[123]`) using a schema from http://jsonschema.net/
```YAML
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "IdList",
  "type": "array",
  "minItems": 1,
  "uniqueItems": false,
  "additionalItems": true,
  "items": {
    "id": "0",
    "type": "integer"
  }
}
```

you get an empty abstract class
```csharp
    public abstract class  IdList 
    {

    } // end class
```

rather than a `public partial class`. 
Does the tool support bare arrays?
If so, how do you define them n the schema?
