### ISSUE TITLE
body: multipart/form-data

### ISSUE THREAD

**Issue by iRodchenkov** [mulesoft-labs/raml-dotnet-tools#77]
Hi!

Thank you for your great product!

Maybe you can help me.

I need method in my controller, which supports file upload from browser. I've found this solution, to define file upload:

```
#%RAML 1.0
title: Example
/uploadFile:
  description: uploads a file
  post:
    body:
      multipart/formdata:
        properties: 
          file:
            description: the file to upload
            required: true
            type: file
```

but when I try to generate controller code, I received this error: 

> Sequence contains no matching element

And if I don't specify body, method is generated with parameter: **[FromBody] string content**

I've watched your code, but haven't found any way to create PUT/POST method without any parameters.

What is the proper way do define method with multipart/form-data body?

Thanks!
