### ISSUE TITLE
Traits parameters applied to the wrong method

### ISSUE THREAD

**Issue by dmalanij** [mulesoft-labs/raml-dotnet-tools#87]
Let's assume we have something like this defined in our RAML

```
/item:
  /{itemId}:
    /comments
      get:
        description: Gets the comments
        is: [pageable]
        responses:
          200:
            body:
              application/json:
                schema: comments
      post:
        description: Saves a comment
        body:
          application/json:
            schema: comment
```
And our trait is defined as 

```
- pageable:
  usage: Applies to collection of items where you need paging
  description: Filters out a single page of the collection
  queryParameters:
    pageSize:
      description: Number of elements in the page
      type: integer
      required: false
      example: 20
      default: 0
    offset:
      description: Page offset
      type: integer
      required: false
      example: 80
      default: 10
```

We're getting the following generated:

```
        [HttpGet]
        [Route("{Id}/comments")]
        public virtual IHttpActionResult GetBase([FromUri] string itemId,[FromUri] int? pageSize= null,[FromUri] int? offset = null) 
```
Which is OK, and
```
        [HttpPost]
        [Route("{Id}/comments")]
        public virtual IHttpActionResult PostBase(Models.Comment comment,[FromUri] string itemId,[FromUri] int? pageSize= null,[FromUri] int? offset = null)
```

Which is wrong.

I've tried using the API Designer of the Anypoint Platform and the trait is correctly applied to just the GET action, not the POST. Didn't have time to debug this but I assume that after parsing, the trait is being incorrectly applied at the resource level rather than the verb itself.
