### ISSUE TITLE
Required attribute missing

### ISSUE THREAD

**Issue by hmts82** [mulesoft-labs/raml-dotnet-tools#92]
Using the following RAML:
```
Mail:
    type: object
    properties:
      Subject:
        maxLength: 100
	required: true
```

The generated model is:
```
[MaxLength(100)]
        public string Subject { get; set; }
```

The generated model doesn't have the required attribute.
